### ISSUE TITLE
Support Sentinel 3 Level-2 Products

### ISSUE THREAD

**Issue by andregracioso** [sertit/eoreader#107]
For example: Fire Radiative Power (FRP)

https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-3-slstr/level-2/fire-radiative-power-frp

When trying:

    s3_folder = "S3B_SL_2_FRP____20230905T234212_20230905T234712_20230906T010030_0299_083_329______MAR_O_NR_002.SEN3"
    prod = Reader().open(s3_folder)

I get:

_There is no existing products in EOReader corresponding to S3B_SL_2_FRP____20230905T234212_20230905T234712_20230906T010030_0299_083_329______MAR_O_NR_002.SEN3_

The data which I tried to read with EOReader was downloaded at the Eumetsat API: https://api.eumetsat.int/data/browse/collections
Collection ID: EO:EUM:DAT:0417

On the other hand, I was able to read Level 1 products from Sentinel 3, SLSTR sensor (RBT).

**Comment by remi-braun** [comment]
Hello,

As stated in other issues, I won't support S3L2 products, sorry for that 😅 
- https://github.com/sertit/eoreader/issues/97
- https://github.com/sertit/eoreader/issues/51

> Sadly Sentinel-3 LST product are not handled by EOReader, as this library focuses on optical band mapping.
See https://github.com/sertit/eoreader/issues/51 for the discussion about the decision (especially https://github.com/sertit/eoreader/issues/51#issuecomment-1243834059 comment)
