### ISSUE TITLE
Name collision between Spectral and Cloud bands

### ISSUE THREAD

**Issue by BastienKovac** [sertit/eoreader#131]
**Describe the bug**

The CloudsBandNames.CIRRUS and SpectralBandNames.SWIR_CIRRUS have the same string name ("CIRRUS"), meaning getting the Cloud band by name by using the _to_band()_ method is currently impossible (as the spectral one is tried first)

**Code To Reproduce**

```python
from eoreader.bands import to_band
print(to_band("CIRRUS"))
```

**Output**

```
[<SpectralBandNames.SWIR_CIRRUS: 'CIRRUS'>]
```

**Environment:**
 - Python version: 3.8.18
 - eoreader version: 0.19.4

**Comment by remi-braun** [comment]
Good one this one 😅

**Comment by remi-braun** [comment]
This should be corrected 😅 
Do you need a release for that or using the latest version from Github is enough for now?

**Comment by BastienKovac** [comment]
Thanks for the quick fix !

I've implemented a quick work-around for my use-case so it can definitely wait for a future release

**Comment by remi-braun** [comment]
Thanks :)
