### ISSUE TITLE
Remove USE_DASK environment variable 

### ISSUE THREAD

**Issue by remi-braun** [sertit/eoreader#189]
Remove useless environment variable `USE_DASK` since Dask will be used if present in environment since sertit 1.43.1

**Comment by guillemc23** [comment]
I was struggling with this at the moment. The environment variable does not have any effect and since eoreader installs `sertit[full]`, it always installs Dask, so I think it's not possible to run an execution without it. I was trying to debug something and wanted to rule out Dask as the culprit 🤔

**Comment by remi-braun** [comment]
Adding dask added a lot of (unexpected) instabilities I need to correct for next release

**Comment by guillemc23** [comment]
but how can i run it without Dask? I can't find a way 😅

**Comment by remi-braun** [comment]
Just remove it from your env I'd say

**Comment by remi-braun** [comment]
@guillemc23 this may help you https://github.com/sertit/sertit-utils/commit/29724e35b6c761f1561e52416ea81046d554e717
(use the latest version of `sertit`)

**Comment by remi-braun** [comment]
v1.44.0 of sertit-utils won't create dask client by default, so this variable is still relevant

**Comment by guillemc23** [comment]
Nice! Thank you @remi-braun

**Comment by remi-braun** [comment]
As per of the latest commits in EOReader:
- I got the CI running smoothly without any client declared (just as before sertit 1.43)
- I got cloudpathlib errors with the multithread client:
```
cloudpathlib.exceptions.OverwriteNewerLocalError: 
Local file (/tmp/tmpodj37zux/sertit-eoreader-ci/optical/SENTINEL2A_20190625-105728-756_L2A_T31UEQ_C_V2-2/MASKS/SENTINEL2A_20190625-105728-756_L2A_T31UEQ_C_V2-2_EDG_R2.tif) 
for cloud path (s3://sertit-eoreader-ci/optical/SENTINEL2A_20190625-105728-756_L2A_T31UEQ_C_V2-2/MASKS/SENTINEL2A_20190625-105728-756_L2A_T31UEQ_C_V2-2_EDG_R2.tif) 
is newer on disk, but is being requested for download from cloud. 
Either (1) push your changes to the cloud, (2) remove the local file, or (3) pass `force_overwrite_from_cloud=True` to overwrite; or set env var CLOUDPATHLIB_FORCE_OVERWRITE_FROM_CLOUD=1.
```

I need to solve that before any new release of EOReader.
