### ISSUE TITLE
ENH: Support S3 LST L2 

### ISSUE THREAD

**Issue by Rapsodia86** [sertit/eoreader#51]
It would be great to support Sentinel-3 LST level 2 product:
https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-3-slstr/product-types/level-2-lst

Unless it is already possible, but after going thru documentation (https://eoreader.readthedocs.io/en/latest/notebooks/why_eoreader.html) I only find level-1, am I correct?

**Comment by remi-braun** [comment]
Hello!

Yes you are correct, L2 products are not handled because they are not used in CEMS rapid mapping 😅

Do you know if they are handled like L1 products ? 
Did you try EOReader geocoding ? Are you satisfied with it ? I am hesitating to swith from my homemade version to the pyresample library

**Comment by Rapsodia86** [comment]
Hi, thanks for a quick answer.
I am not familiar with L1 or L2 products since I find the whole idea of S3 dataset geometry structure and requirement of using SNAP really tedious.
I do work with MODIS LST & Landsat data. 
None of them requires more than gdal & numpy to be processed, and that is why I do not use any other libraries.
But at some point, I will have to add Sentinel data. There is quite a lot of scripts/tools/libraries for S2, but not much for S3.  
While looking for the approach (outside SNAP) to transform (and reproject)  S3 LST L2 to geotiff, I found your EOReader library. 
So, had no chance to try it. 
Are you interested in adding LST L2? I think that would be a very first version of processing w/o SNAP. Unless, there is something out there, which I cannot locate.

**Comment by remi-braun** [comment]
I think I will handle this product, especially since it seems easier to handle than L1 products.(S3-L1 products are soooo hard to handle correctly, it is a pity 🙄 )

But this may take some time. I will try to add it to the 0.17.0 but I wont promise anything 😅

**Comment by Rapsodia86** [comment]
Sounds great! 
If need any help, please let me know!

**Comment by remi-braun** [comment]
So I was on holidays last week, and I just looked deeper into S3 L2-LST data 😅 
If I'm right, LST products don't offer spectral bands anymore, only processed data (the whole point of LST haha).

So, I will not implement them (sadly), as the point of EOReader is to map spectral bands between sensors (for optical data) but not to handle any type of product.

However, I think you can automatize the geocoding (and conversion to GeoTiff) quite easily.
It seems there is only one grid, so it simplifies the processing.
You can look at this [tutorial](https://lpdaac.usgs.gov/resources/e-learning/working-ecostress-evapotranspiration-data/) (➡️ #3b.-Define-Projection-and-Output-Grid)  to see how to handle lat/lon files in Python.

If you have questions, feel free to ask here 😉

**Comment by Rapsodia86** [comment]
Ok, I will explore the tutorial and see how the resulting image compares with SNAP's output product. If that works, I can share the script if interested.
Thanks!

**Comment by remi-braun** [comment]
> If that works, I can share the script if interested.


Yes I would be very interested !
I think this should follow the tutorial but a confirmation would be great ! 🙏

**Comment by Rapsodia86** [comment]
Hi Remi, I do have a few questions ,and since you have already dealt with S3 I hope you can provide me with answers. Do you mind sending me an email so I can reach you? monikat@msu.edu

If not, then I will elaborate here:)

**Comment by remi-braun** [comment]
Email sent :)

However, when reaching a runnable script, it should be nice to post it here 😉

**Comment by remi-braun** [comment]
For information, as for [release 0.18.0](https://github.com/awesome-spectral-indices/awesome-spectral-indices/blob/main/output/spectral-indices-table.csv), Sentinel-3 geocoding is using `pyresample` 😄

**Comment by Rapsodia86** [comment]
Thank you for the information!
