### ISSUE TITLE
Missing ogr2ogr in PATH: error in ‘wgs84_extent’ when processing Sentinel-1 products

### ISSUE THREAD

**Issue by TK12331** [sertit/eoreader#60]
Assigning CRS to a GeoDataFrame without a geometry column is not supported. Use GeoDataFrame.set_geometry to set the active geometry column.
Traceback (most recent call last):
  File "d:\SAR_DATA\process\eoreader-main\eoreader\products\sar\s1_product.py", line 187, in wgs84_extent
    raise InvalidProductError(
eoreader.exceptions.InvalidProductError: Cannot determine the WGS84 extent of S1A_IW_GRDH_1SDV_20200308T121318_20200308T121343_031584_03A39B_5C41

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10992\.conda\envs\DL1\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\10992\.conda\envs\DL1\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\10992\.vscode\extensions\ms-python.python-2022.5.11221002\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\10992\.vscode\extensions\ms-python.python-2022.5.11221002\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\10992\.vscode\extensions\ms-python.python-2022.5.11221002\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\10992\.conda\envs\DL1\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\10992\.conda\envs\DL1\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\10992\.conda\envs\DL1\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\SAR_DATA\process\eoreader-main\K.py", line 15, in <module>
    s1_prod.wgs84_extent()
  File "C:\Users\10992\.conda\envs\DL1\lib\site-packages\methodtools.py", line 72, in __call__
    return self.__call__(*args, **kwargs)
  File "d:\SAR_DATA\process\eoreader-main\eoreader\__init__.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "d:\SAR_DATA\process\eoreader-main\eoreader\products\sar\s1_product.py", line 196, in wgs84_extent
    raise InvalidProductError(ex) from ex
eoreader.exceptions.InvalidProductError: Cannot determine the WGS84 extent of S1A_IW_GRDH_1SDV_20200308T121318_20200308T121343_031584_03A39B_5C41

**Comment by TK12331** [comment]
I follow the tutorial and here is my code:

from eoreader.reader import Reader
from eoreader.bands import *
import sys
sys.path.append('D:/Software/SNAP/snap/bin/')

# Sentinel-1 GRD path
s1_path = "E:\SAR_DATA\Sentinel1\S1A_IW_GRDH_1SDV_20200308T121318_20200308T121343_031584_03A39B_5C41.zip"
# s1_path = "E:\SAR_DATA\ESA\TSX_OPER_SAR_SC_GEC_20110223T012215_N24-000_W111-445_0000_v0100.sip\TSX_OPER_SAR_SC_GEC_20110223T012215_N24-000_W111-445_0000.zip"

# Create the reader object and open satellite data
reader = Reader()

# The reader will recognize the constellation from its product structure
s1_prod = reader.open(s1_path)

# Load some bands and index
s1_prod.get_band_paths([VV, HH])


An error occured, and I checked into the inner function and found the error is through in function of 'eoreader/products/sar/s1_product.py':
s1_prod.wgs84_extent()

When run the code 'extent_wgs84 = vectors.read(preview_overlay)', it will throw the message:
Assigning CRS to a GeoDataFrame without a geometry column is not supported. Use GeoDataFrame.set_geometry to set the active geometry column.

Finally, the code 'vect.crs = WGS84' throw the error.


How can I solve this problem? Thanks in advance!

**Comment by TK12331** [comment]
Besides, I read the message that 
![image](https://user-images.githubusercontent.com/76766406/204271214-c2a5d0c0-ce97-4af0-8314-61f6857ba344.png)

**Comment by remi-braun** [comment]
Hello,

Do you have `ogr2ogr` accessible as pointed out in the latest [FAQ](https://eoreader.readthedocs.io/en/latest/faq.html#sar-data-fails-to-load-extent) ? 
For some reason Sentinel-1 KML files sometimes fails to be read by geopandas (I don't know why) and I need to convert them to geojson thanks to `ogr2ogr` as a workaround.
To know if you have it available, just type `ogr2ogr` in a terminal. If the help section is displayed, it will work.
However, you are right, I should better handle this error (at least throw a proper exception).

Concerning your last comment, I don't use `snappy` as it is slmow and buggy. We run `SNAP GPT` directly.
If you have properly installed SNAP, this should work. Once again, to check if `gpt` is available, just type it in a terminal. If the help section is displayed, it will work.

**Comment by TK12331** [comment]
That worked for me.  Thank you!

**Comment by TK12331** [comment]
That worked for me. Thank you!

> Do you have `ogr2ogr` accessible as pointed out in the latest [FAQ](https://eoreader.readthedocs.io/en/latest/faq.html#sar-data-fails-to-load-extent) ? For some reason Sentinel-1 KML files sometimes fails to be read by geopandas (I don't know why) and I need to convert them to geojson thanks to `ogr2ogr` as a workaround. To know if you have it available, just type `ogr2ogr` in a terminal. If the help section is displayed, it will work. However, you are right, I should better handle this error (at least throw a proper exception).

**Comment by remi-braun** [comment]
🙏
