### ISSUE TITLE
How to set os.environ[DEM_PATH] correctly?

### ISSUE THREAD

**Issue by TK12331** [sertit/eoreader#61]
In FAQ I read
<img width="446" alt="11" src="https://user-images.githubusercontent.com/76766406/204470224-19ddf30e-4f38-4585-8444-86cf8df5eac3.png">
if I want to use the default setting as the DEM of SNAP, how can I find the specific path?

**Comment by remi-braun** [comment]
If you want to use i.e. COPDEM-30, just type:

```python
import os
os.environ[DEM_PATH] = "Copernicus 30m Global DEM"
```

But I just saw that the default is not `GETASSE30` anymore (it was when `COPDEM-30` wasn't existing or was buggy).
I will change that 😄 

You can find that piece of code with a custom DEM `[here](https://eoreader.readthedocs.io/en/v0.17.0/notebooks/SAR.html#load-bands)`

**Comment by remi-braun** [comment]
I updated the documentation of [SAR notebook](https://eoreader.readthedocs.io/en/latest/notebooks/SAR.html) to add a paragraph about your question 😉

**Comment by remi-braun** [comment]
To load DEM-related bands, you need to provide a DEM on your own as specified [here](https://eoreader.readthedocs.io/en/latest/notebooks/SAR.html#load-bands).
(I cannot use SNAP DEMs as the software downloads the tiles on the spot...) 

You may have more information about that in the [DEM notebook.](https://eoreader.readthedocs.io/en/latest/notebooks/dem.html)

**Comment by remi-braun** [comment]
However, your current bug seems to come from another source, could you create another issue with full log trace ?

**Comment by TK12331** [comment]
OK, I create a new one right now.
