### ISSUE TITLE
The alignment between EOReader and SNAP

### ISSUE THREAD

**Issue by TK12331** [sertit/eoreader#65]
I process Sentinel-1 data with SNAP before, and now I want to align the processing results between EOReader and SNAP. 
I process GRD product using EOReader with step: 
`Apply-Orbit-File` -> `ThermalNoiseRemoval` -> `Remove-GRD-Border-Noise` -> `Calibration `-> `Terrain-Correction`. (for comparing the value of pixel, I remove step `LinearToFromdB` currently.

The name of the GRD product I use is S1A_IW_GRDH_1SDV_20200308T121318_20200308T121343_031584_03A39B_5C41.zip, whose image shape is 25847 x 16731.

However, I found some problems as followes:
1. Comparation between`Calibration` product
The value of tif file I generated from SNAP is 0-255(float64,but all the decimal value is 0), while the value of tif file I generated from EOReader is 0-123.4. Besides, the scale value between corresponding pixels is not constant.

2. Comparation between `Terrain-Correction` product
The value problem is as same as 1. 
The shape of tif file I generated from SNAP is 31668 x 21478, while the shape  of tif file I generated from EOReader is 14372 x 10790.

Why they aren't alignment? Or am I missing something?

**Comment by remi-braun** [comment]
What is the resolution of your SNAP product ? By default EOReader sets a 20m resolution to Sentinel-1 IW GRD products as stated and explained [here](https://eoreader.readthedocs.io/en/v0.17.0/sar.html#sentinel-1).
Maybe SNAP sets another default resolution ?

It may also come from another CRS reprojection. EOReader reprojects everything in UTM when SNAP does not if I'm not mistaken.

You can try a `gdalinfo` on the both files to check their respective resolution and CRS.

If you want to modify the graphs, just follow [this section](https://eoreader.readthedocs.io/en/v0.17.0/sar.html#what-to-know-if-you-are-changing-a-graph).

Moreover, for discussions could you post in the `discussions` section please ? I would like to keep this section for bugs and enhancements 😄 
And don't hesitate to look through the documentation before asking here, a lot of what you ask is already there 😉

**Comment by TK12331** [comment]
OK, I will post it in the discussion. Thank you!😉

**Comment by remi-braun** [comment]
Your comments triggered an intense discussion here at SERTIT (thanks for this 😄)
➡️ Should we load bands to the resolution rg*az or to the pixel spacing (i.e. with [these given values](https://sentinel.esa.int/web/sentinel/user-guides/sentinel-1-sar/resolutions/level-1-ground-range-detected))

Before today, we decided to orthorectify data to the "real" resolution (ie rg*az), in order to save space (images are smaller) and by knowing that objects under this minimum mapping unit wouldn't be resolved.

However, we realised that this may disorient the user as this isn't the common habits, so we will use the given pixel spacing as default resolution for SAR data, i.e. 10m for S1 GRD IW 😄

**Comment by remi-braun** [comment]
Sorry for my afterthought, but we have to follow [CEMS](https://emergency.copernicus.eu/mapping/#zoom=2&lat=17.44093&lon=29.71939&layers=00B0T) resolutions defines in the [Data Access Portfolio (2014-2022, section 6.2)](https://spacedata.copernicus.eu/documents/20126/0/DAP+Document+-+current+(10).pdf) as EOReader is first built for CEMS activations 😅 

I will then only update resolutions for products that are not in this document. (you see that S1 GRD IW are at 20m resolution there)

**Comment by remi-braun** [comment]
Does this answer to your question ?

**Comment by TK12331** [comment]
Oh, thanks for your reply! which makes me understand more about SAR data processing.
You mentioned about SERTIT, what's that?

However, I still can not align the output tiff with SNAP and EOReader: As mentioned before, the value of tif file I generated from SNAP using `export tiff` is 0-255(float64,but all the decimal value is 0), while the value of tif file I generated from EOReader is 0-123.4(float64). Besides, the scale value between corresponding pixels is not constant. 

For afterward image processing, I want to align the data produced by SNAP and EOReader, so I want to make sure the distribution of my SAR data is consistent.

How can I make it?

**Comment by remi-braun** [comment]
In must say, it is really unlikely that your SAR data stays in integer 
Could you post the two graphs you used for producing these rasters ? 😀

**Comment by TK12331** [comment]
It seems that `export tiff` in SNAP do some normalization...

Now I use Geo-Tiff to make alignment, the XML for SNAP and EOReader are added in attachment.
[graph.zip](https://github.com/sertit/eoreader/files/10145965/graph.zip)

**Comment by TK12331** [comment]
It seems that `export tiff` in SNAP do some normalization...

Now I use Geo-Tiff from SNAP to make alignment, the XML for SNAP and EOReader are added in attachment.
[graph.zip](https://github.com/sertit/eoreader/files/10145965/graph.zip)

**Comment by TK12331** [comment]
I use GDAL to read tiff file, the middle name `ge` means the geo-tiff from SNAP, while `eo means the tiff from EOReader.
![image](https://user-images.githubusercontent.com/76766406/205431812-d892fdfc-ba2f-47a0-9f05-4c151ab299f5.png)

**Comment by remi-braun** [comment]
> It seems that `export tiff` in SNAP do some normalization...
> 
> Now I use Geo-Tiff from SNAP to make alignment, the XML for SNAP and EOReader are added in attachment. [graph.zip](https://github.com/sertit/eoreader/files/10145965/graph.zip)

I see that the two graphs are different.
In EOReader you left the `Thermal Noise Removal` step. Could you test this again with exact same graphs ?

**Comment by TK12331** [comment]
OK, I test the same graphs right now.

The `thermal Noise Removal` is done in original product, SNAP will raised an error, would EOReader continue to process this step?

Besides, u can check the comparison result I update above, it seems that they are very close ... (the mean of their difference for each pixel is just 0.003)

From your opinion, are they alignment?

**Comment by remi-braun** [comment]
From what I recollect, your comparison is flawed as the graphs are no exactly the same.
(or I didn't understand this sentence: 
> The thermal Noise Removal is done in original product, SNAP will raised an error, would EOReader continue to process this step?

)

Moreover, as I am using directly SNAP without any modification, I wouldn't understand discrepancies (and I wouldn't know how to fix them).

Eventually, these discrepancies, as you underlined, are thin. So I personally wouldn't bother to check it more, for the following reason :
➡️ You will add a terrain correction step after that that will resample everything, mixing speckle noise from every neighbouring pixels, so the absolute pixel values are not really making sense. Not to mention the despeckling step that will do that a lot more.

**Comment by remi-braun** [comment]
Ok, I am closing this ;)
