### ISSUE TITLE
Capella data not loading

### ISSUE THREAD

**Issue by koles289** [sertit/eoreader#76]
Hello

I would like to ask some clarification regarding support for CAPELLA data for SAR.
I have a zip file with CAPELLA data, but when I try to load the file, the outputting variable is empty and the code is not throwing any errors.
When I was checking the reader function, it seems to me, that there is missing a class creation for Capella data and this is why it does not throw any error.
Could you help me to understand if there is currently a support for Capella satellite?

**Comment by remi-braun** [comment]
Hello, 

Could you precise the EOReader version you are using ? 
The 0.19.0 has only be up for several minutes (and not yet available on conda), so maybe you just have to update EOReader 😅

**Comment by remi-braun** [comment]
Moreover, archived Capella won't work (see https://eoreader.readthedocs.io/en/v0.19.0/sar.html#implemented-sar-constellations).
You must extract the folder before (SNAP cannot use archived Capella products directly)

If you want to display EOReader logs, you can initialize le EOReader logger like in this :
```python
# Create logger
import logging
from sertit import logs

logs.init_logger(logging.getLogger("eoreader"))
```

(from [this](https://eoreader.readthedocs.io/en/v0.19.0/notebooks/custom.html) notebook)

**Comment by remi-braun** [comment]
Happy to see you made it work 🎆
