### ISSUE TITLE
Coordinates doesn't match between metadata and plot

### ISSUE THREAD

**Issue by sorny92** [sertit/eoreader#87]
I just started using EOReader.

I'm following this link: https://eoreader.readthedocs.io/en/v0.19.4/notebooks/windowed_reading.html
As I want to visualize a POLYGON over an image of sentinel-2.

The polygon I want to plot is something like this:
`"POLYGON ((-7.5262454743456715 39.66672692059894, -7.5238403916980525 39.66669637036892, -7.523853372713001 39.666086466637324, -7.52625843422954 39.666117016209796, -7.5262454743456715 39.66672692059894))"`

The image I want plot with it has a metadata where the footprint is something like this:
```xml
            <Product_Footprint>
                <Global_Footprint>
                    <EXT_POS_LIST>39.744399896499196 -7.832855 39.72445184157785 -6.552124 38.73593643111066 -6.5862427 38.75519833855342 -7.849121 39.744399896499196 -7.832855 </EXT_POS_LIST>
                </Global_Footprint>
            </Product_Footprint>
```
As you can see my polygon should be contained on the image.

The problem I'm finding is that once I load the image following the code and I plot just the image I get the next coordinates.
![Screenshot from 2023-04-18 22-33-34](https://user-images.githubusercontent.com/8601395/232901782-8b709670-ff78-4f09-8d7a-8afe83d4d509.png)

As you can see in the previous image the range of x and y coordinates is aroung 1e5-1e6.

My code looks like this:
```python
polygon_str = "POLYGON ((-7.5262454743456715 39.66672692059894, -7.5238403916980525 39.66669637036892, -7.523853372713001 39.666086466637324, -7.52625843422954 39.666117016209796, -7.5262454743456715 39.66672692059894))"
wkt_polygon = wkt.loads(polygon_str)
polygon = gpd.GeoDataFrame(index=[0], crs=prod.crs(), geometry=[wkt_polygon])
polygon = polygon.to_crs(prod.crs())
polygon.plot()

# To load the image I just do this:
prod = Reader().open(filename)
bands = prod.load([GREEN])        
bands[GREEN][:, ::10, ::10].plot()

```

I'm assuming I'm missing some transformation somewhere as this data is just a .safe downloaded from SNAP.

**Comment by remi-braun** [comment]
Hey!

I'm glad you want to use EOReader 😄 

You cannot use only `plot` to overlap geographical plots, one will only juxtapose over the other.
A good way to do this is to use `hvplot` with `geoviews` and to do as I've done in [this cell](https://eoreader.readthedocs.io/en/v0.19.4/notebooks/windowed_reading.html#plot).

And don't forget to import this: 
```python
import hvplot.pandas
import hvplot.xarray

hvplot.extension('matplotlib')
```

PS: This is not an EOReader bug 😉

**Comment by remi-braun** [comment]
No problem for your questions!
The coordinates you see are those in [UTM](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system) which are in meters. If your not familiar with projections, you should read a bit about them and the difference between geographic (lat/lon, i.e. `epsg:4326`) and projected ones (UTM, i.e. `epsg:32[67]\d\d`).

If you really want to have lat/lon coordinates in your plot, you should reproject your raster ti `epsg:4326` before plotting. You can use [`rioxarray.reproject`](https://corteva.github.io/rioxarray/stable/examples/reproject.html#Reproject) to achieve it.

**Comment by sorny92** [comment]
> If you really want to have lat/lon coordinates in your plot, you should reproject your raster to epsg:4326 before plotting. You can use [rioxarray.reproject](https://corteva.github.io/rioxarray/stable/examples/reproject.html#Reproject) to achieve it.

I understand that reproject will actually wrap the whole image so this is not super efficient and I'm better of converting the polygon to UTM, am I right?

Nevertheless, thanks for your help!

**Comment by remi-braun** [comment]
> I understand that reproject will actually wrap the whole image so this is not super efficient and I'm better of converting the polygon to UTM, am I right?

You are already doing it here 😉 :

```python
polygon = polygon.to_crs(prod.crs())

**Comment by sorny92** [comment]
> > I understand that reproject will actually wrap the whole image so this is not super efficient and I'm better of converting the polygon to UTM, am I right?
> 
> You are already doing it here wink :
> 
> ```python
> polygon = polygon.to_crs(prod.crs())
> ```

Well this is part of my confusion. As I understood, this should have work to conver py polygon to the same crs of the image but it keeps it more or less at the same.

I will play with it a bit later.

Thanks for your help!
