### ISSUE TITLE
How use the py lib to preprocess sentinel 1a or 1b sar data?

### ISSUE THREAD

**Issue by funny000** [sertit/eoreader#92]
**Is your feature request related to a problem? Please describe.**

I want to use python to preprocess sentinel 1a or 1b, for example trajectory correction\thermal noise removal\calibration...so on, and I to search the function in the eoreader api document, but don't find the corresponding function.
**Describe the solution you'd like**
when i search sentinel 1a or 1b function or py lib in the web, I find the snappy lib can solve the problem, 
So the snappy lib with the eoreader lib is same in the process sentinel 1a\b sar data?

**Comment by remi-braun** [comment]
Hello,

EOReader processing of Sentinel-1 data is done through SNAP via a GPT graph.
You can find them here : https://github.com/sertit/eoreader/tree/main/eoreader/data

You can customize these YAML files following the documentation: https://eoreader.readthedocs.io/en/latest/sar.html#gpt-graphs

However, pay attention that EOReader will only be able to deal with GRD data and will automatically orthorectify SLC data.

**Comment by remi-braun** [comment]
Did you manage to solve your problem ? 
I will close this issue in case of no answer 😅
