### ISSUE TITLE
eorader is not opening Sentinel3 S3*_SL_2_LST__ Products

### ISSUE THREAD

**Issue by JonnyReGIF** [sertit/eoreader#97]
Hello all, 

up on my journey exploring Sentinel 3 LST data i stumbeld over the awesome eoreader library. 

But unfortunately I am not able to read the S3 Thermal product.  I Run the following code, with the files downloaded via the sentinelsat API 

Thanks in advance, hopefully i dont oversee a simple mistake here :) 
(This is my first Issue on Github, please let me know how to improve the questioning/reporting)

**Code To Reproduce**

```python 

# sentinelsat query
from sentinelsat import SentinelAPI, read_geojson, geojson_to_wkt

api = SentinelAPI(######, #######, "https://apihub.copernicus.eu/apihub", show_progressbars  = True)

products = api.query(aoi, 
                     date=("20230604", "20230612"), 
                     platformname = "Sentinel-3",
                     #filename = "filname:SL_2_LST___",
                     #cloudcoverpercentage = (0, 100),
                     instrumentshortname='SLSTR',
                     producttype = 'SL_2_LST___',   
                     #area_relation = 'Contains',
                     #cloudcoverpercentage = (0, 10)
                     )

# EOReader
from eoreader.reader import Reader
from eoreader.bands import *

reader = Reader()

prod = reader.open(product_path="D:\MA\s3_neu  \S3A_SL_2_LST____20230604T064000_20230604T064300_20230605T162514_0179_099_291_2160_PS1_O_NT_004.SEN3", output_path=base_path,
constellation="S3_SLSTR", remove_tmp=True)

print(product)

```

**Output**
2023-06-16 11:08:25,317 - [WARNING] - There is no existing products in EOReader corresponding to [D:\MA\s3_neu\S3A_SL_2_LST____20230604T064000_20230604T064300_20230605T162514_0179_099_291_2160_PS1_O_NT_004.SEN3](file:///D:/MA/s3_neu/S3A_SL_2_LST____20230604T064000_20230604T064300_20230605T162514_0179_099_291_2160_PS1_O_NT_004.SEN3)

None

**Environment:**
 - Python version: `Python 3.11.2`
 - sertit-utils version: `'0.20.0'`

**Comment by remi-braun** [comment]
Hello,

Thanks for your issue ! This is a really good habit to take 😉

Sadly Sentinel-3 LST product are not handled by EOReader, as this library focuses on optical band mapping.
See #51 for the discussion about the decision (especially [this](https://github.com/sertit/eoreader/issues/51#issuecomment-1243834059) comment)

Sorry for that

**Comment by JonnyReGIF** [comment]
Thanks for the kind and quick Answer :) 

I thing, things should get going with the tutorial you mentiond in the comment :)

**Comment by remi-braun** [comment]
Fyi you can look at the [code](https://github.com/sertit/eoreader/blob/1c0195cde24831b4b2dae8f97fbf4d862900dcca/eoreader/products/optical/s3_product.py#L634)  I made for Sentinel-3 geocoding, I implemented the pyresample method 😉 It works like a charm !
